import twColors from "tailwindcss/colors";

export const colors = {
  "--un-prose-body": twColors.slate[700],
  "--un-prose-headings": twColors.slate[900],
  "--un-prose-lead": twColors.slate[600],
  "--un-prose-links": twColors.slate[900],
  "--un-prose-bold": twColors.slate[900],
  "--un-prose-counters": twColors.slate[500],
  "--un-prose-bullets": twColors.slate[300],
  "--un-prose-hr": twColors.slate[200],
  "--un-prose-quotes": twColors.slate[900],
  "--un-prose-quote-borders": twColors.slate[200],
  "--un-prose-captions": twColors.slate[500],
  "--un-prose-code": twColors.slate[900],
  "--un-prose-pre-code": twColors.slate[200],
  "--un-prose-pre-bg": twColors.slate[900],
  "--un-prose-th-borders": twColors.slate[300],
  "--un-prose-td-borders": twColors.slate[200],
  "--un-prose-invert-body": twColors.slate[300],
  "--un-prose-invert-headings": twColors.white,
  "--un-prose-invert-lead": twColors.slate[400],
  "--un-prose-invert-links": twColors.white,
  "--un-prose-invert-bold": twColors.white,
  "--un-prose-invert-counters": twColors.slate[400],
  "--un-prose-invert-bullets": twColors.slate[600],
  "--un-prose-invert-hr": twColors.slate[700],
  "--un-prose-invert-quotes": twColors.slate[100],
  "--un-prose-invert-quote-borders": twColors.slate[700],
  "--un-prose-invert-captions": twColors.slate[400],
  "--un-prose-invert-code": twColors.white,
  "--un-prose-invert-pre-code": twColors.slate[300],
  "--un-prose-invert-pre-bg": twColors.slate[950],
  "--un-prose-invert-th-borders": twColors.slate[600],
  "--un-prose-invert-td-borders": twColors.slate[700],
};

export const invertColors = {
  "--un-prose-body": "var(--un-prose-invert-body)",
  "--un-prose-headings": "var(--un-prose-invert-headings)",
  "--un-prose-lead": "var(--un-prose-invert-lead)",
  "--un-prose-links": "var(--un-prose-invert-links)",
  "--un-prose-bold": "var(--un-prose-invert-bold)",
  "--un-prose-counters": "var(--un-prose-invert-counters)",
  "--un-prose-bullets": "var(--un-prose-invert-bullets)",
  "--un-prose-hr": "var(--un-prose-invert-hr)",
  "--un-prose-quotes": "var(--un-prose-invert-quotes)",
  "--un-prose-quote-borders": "var(--un-prose-invert-quote-borders)",
  "--un-prose-captions": "var(--un-prose-invert-captions)",
  "--un-prose-code": "var(--un-prose-invert-code)",
  "--un-prose-pre-code": "var(--un-prose-invert-pre-code)",
  "--un-prose-pre-bg": "var(--un-prose-invert-pre-bg)",
  "--un-prose-th-borders": "var(--un-prose-invert-th-borders)",
  "--un-prose-td-borders": "var(--un-prose-invert-td-borders)",
};
